trigger: none

pool: dev-infra-pool
stages: 
 - stage: buils
   displayName: Terraforminstall
   jobs:
     - job: Terraforminstall
       displayName: Terraforminstall
       steps: 

       - task: TerraformInstaller@1
         inputs:
           terraformVersion: 'latest'

       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
           backendServiceArm: 'kashi-dev-app'
           backendAzureRmResourceGroupName: 'shashi_rg'
           backendAzureRmStorageAccountName: 'shashistg01'
           backendAzureRmContainerName: 'shashicontainer'
           backendAzureRmKey: 'terraform.tfvars'